"""add parent_id to artifacts

Revision ID: 7de6e7320caa
Revises: 0006
Create Date: 2026-05-29 04:43:16.125262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7de6e7320caa'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'artifacts', 'artifacts', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artifacts', type_='foreignkey')
    op.drop_column('artifacts', 'parent_id')
    # ### end Alembic commands ###
