"""Add summary_text, suggested_questions, clinical_manifest to consultations

Revision ID: b3ccf3b475bd
Revises: 7de6e7320caa
Create Date: 2026-05-29 06:42:20.639916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3ccf3b475bd'
down_revision: Union[str, None] = '7de6e7320caa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('summary_text', sa.Text(), nullable=True))
    op.add_column('consultations', sa.Column('suggested_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('consultations', sa.Column('clinical_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultations', 'clinical_manifest')
    op.drop_column('consultations', 'suggested_questions')
    op.drop_column('consultations', 'summary_text')
    # ### end Alembic commands ###
